# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encoder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'encoder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rencoder.proto\x12\x07\x65ncoder\"0\n\rEncodeRequest\x12\x0b\n\x03mel\x18\x01 \x01(\x0c\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\"\x1c\n\x0e\x45ncodeResponse\x12\n\n\x02xa\x18\x01 \x01(\x0c\"0\n\rDecodeRequest\x12\x0b\n\x03mel\x18\x01 \x01(\x0c\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\"\x1e\n\x0e\x44\x65\x63odeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2\x88\x01\n\x07\x45ncoder\x12\x39\n\x06\x45ncode\x12\x16.encoder.EncodeRequest\x1a\x17.encoder.EncodeResponse\x12\x42\n\x0f\x45ncodeAndDecode\x12\x16.encoder.DecodeRequest\x1a\x17.encoder.DecodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encoder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCODEREQUEST']._serialized_start=26
  _globals['_ENCODEREQUEST']._serialized_end=74
  _globals['_ENCODERESPONSE']._serialized_start=76
  _globals['_ENCODERESPONSE']._serialized_end=104
  _globals['_DECODEREQUEST']._serialized_start=106
  _globals['_DECODEREQUEST']._serialized_end=154
  _globals['_DECODERESPONSE']._serialized_start=156
  _globals['_DECODERESPONSE']._serialized_end=186
  _globals['_ENCODER']._serialized_start=189
  _globals['_ENCODER']._serialized_end=325
# @@protoc_insertion_point(module_scope)
